language: rust

matrix:
  fast_finish: true
  include:
    # x86_64-apple-darwin
    - name: "x86_64-apple-darwin - Rust stable 1.18.0 - xcode10"
      env: TARGET=x86_64-apple-darwin
      rust: 1.18.0
      os: osx
      osx_image: xcode10
    - name: "x86_64-apple-darwin - Rust beta - xcode10"
      env: TARGET=x86_64-apple-darwin
      rust: beta
      os: osx
      osx_image: xcode10
    - name: "x86_64-apple-darwin - Rust nightly - xcode10"
      env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
      osx_image: xcode10
    - name: "x86_64-apple-darwin - Rust stable 1.18.0 - xcode6.4"
      env: TARGET=x86_64-apple-darwin
      rust: 1.18.0
      os: osx
      osx_image: xcode6.4
    - name: "x86_64-apple-darwin - Rust beta - xcode6.4"
      env: TARGET=x86_64-apple-darwin
      rust: beta
      os: osx
      osx_image: xcode6.4
    - name: "x86_64-apple-darwin - Rust nightly - xcode6.4 !"
      env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
      osx_image: xcode6.4


script: ci/run.sh
